language: R
sudo: required
warnings_are_errors: true
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
  - bash <(curl -s https://codecov.io/bash)

## Use patched devtools
r_github_packages:
  - hadley/devtools@efa894ffa